name = "FlorestalFunctions"
uuid = "5524159d-8b2c-4e98-8697-462d3b06eaac"
authors = ["renilsonlisboa <renilsonlisboajunior@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
QML = "2db162a6-7e43-52c3-8d84-290c1c42d82a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
